### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by Po-Ting-lin** [yohschang/phase_retrival#2]
Where can I find the reference(paper) for this?

https://github.com/yohschang/phase_retrival/blob/c4b293ec6694786478a483bbdb4d93cfac1186d3/phase_retrival.py#L15

**Comment by yohschang** [comment]
Fast phase processing in off-axis holography by CUDA including parallel phase unwrapping
Ohad Backoach, Saar Kariv, Pinhas Girshovitz, and Natan T. Shaked

Theory can be found in the above paper. However, this method does not perform better than "scipy unwrap" when dealing with larger figure(lager than 1024*1024)

BTW, this method is written by Yang Hsian Lin, I have no idea how it works :)

**Comment by Po-Ting-lin** [comment]
OK! Interesting
I tried to translate your repo into cuda version. :)
https://github.com/Po-Ting-lin/PhaseRetrievalDPM
